language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "dogonfire"
    token:
      secure: "a8W9E0mmMJZSYcxQUzqnB/3GMvckRo3r4u05vOgoSn2dZbTARh/+K8ALl59WDz1urm3Zw4otbbBH5L1lipOG9tnmVhwBYvnLa8eQaQsCcvb+96W3Y7EsQB4XwsEi8C4N/HZX0O0N8gl/yNbJO41FCvBS40BSbdRZcccVw8xONo7TaM9/hBU/h3NA9K0ChBrLmE5ideGwZZjGD46LfJsTjC7CBSNawL6lC4/sFvHz7ZsccvfdmRapC/tdY3qGESIk4NgSeHYnKGcpwjJB2svw0j528I57CcVEElmMxOPtvPGV1udLFiU/NjyVCiubJYzLKWzuV9MY7xhnroRQoRkxDJ4Oh3WWhQ0RBmEsN8qj2nVoSi6fg18M1YECGk4xkCHcuQOdAYB0FnoRnScLeQPO5Q3Gl5aUc/DCVpqZJb9VWD+yflFx4hZIhGVeObswV7tzrEMO1wvKPegXKv5FsGCecsNvBDSeIvAVb44Ld5HbjqZWAMW+4dxiJa6I0VwfAJJwVtLx05MW8BlOVGUyI6DbyTndgsKIL0w5pzRnxCDNEmahcJm2E8e2fOF0jytFkdtyQNJRpLMx8sqD2c2/7MzdayrbMhBwTTtmRFIowF14T5AwAyg/oDLSGTdqxOdLFzRJJjvISt9O6UOrPr6w4VQo9/hzWjUjUhVXvathBLwWl1o="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DogOnFire_DramaCraft