language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "dogonfire"
    token:
      secure: "f9cBA/Ujrv3Q7zCMNaLfGE/6/cAmrvEiHqlPh4yz18dOK2JaUTQJPxno//Bvl0rNQcGQYaf+McQ9aiCG0r7gTf0HK+GtTXr7ErBJ4h8kTEAYpxz+l/0y/KpLa1XEcLary9sTpUhVnVfF8ml6hAadxQxVQn7/2o/fAvvmE9WJU/KQbHiE811014bDoioRLUsVHix+6ySigeUHz67anSn+yNofKDnDFxh76zO59zTtSdHTjmcTfK3JAk+g1jAYoc0kLat2wOkC/8orJFBjXEVkOODMfKvhLoDzezIZDU+RZ3HdeRMBJFf9hMkBR7pqMTR0wfM/MnP8D/WaKNoSiaNutNCjzcjaJtFZZoPNlN7yxlB2sSTx9d+ais51husjPnX3HxwIURYns57BOdTAktUL6UEs6xi032zwNBlPDq5xKsJV5JTwL0fYrKTYKpAnhsLDl6pDxiukmVYUJkw5fA++g4yA3aQ9somAULrx/bq0kFBb0cf+7BgGC3R1ZboJ2FlJymeQJJM6YGdEr57qw2GV9LMXczcJvG+HHfx/thcb9ThHFa1TreVY7+ttd1bXwJPxSEiaWWPhT+lAro4ObCXmVKsRyJwh6vOvaPO0vN/9eydB0XaDsmSArK6BoRHtNjXt6ivVFtkXP20iDWVwQekfpDGzFDAfW7DCHOAAniOroNI="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DoggyCraftDK_DramaCraft