language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "dogonfire"
    token:
      secure: "k8RZ7H9SZTLnSu8cS6iOsCRiNndeggWVsrQ4fNEs1KgWNCALnoah4/9U7YCLhJU4Lbpw6bkN4zSNdW6p/8ebTyuQM0F/kuvmKYoImLiOMxSvz71oa6WsZ0iJBSqgEblxPmi4ebfZUmemvwHaLEcBsc+qPZ2zrfG8aR086aZOp8JSNBBLnMrEdX+gR9x38lQFbDoTLxqbQzMg/vemiRxz+qqdVH+RrNJoJkBLMbRW83ZpjVxkddT2f+7xyjN59RnmMi0shPJb5C+Nuu07RhnmewDx26MpE5XC5ecjHv5H268+He5STfsnTT5YOJEGDDI69tfCyj2rSRFaDQixF4mEg1P00VR7la8UvakDuSaLTof5Ytsq2SPv7d9tAv+XFSMbKfgse38qG9GXRQeSIHnhkZncILjeqAAlFZr9fH/t1trUZv5mbsFy4qHbLDg6RtoYB31Q2HYhdhFAx3lPe+jgvBvEFo7gE3AjD/gNaM7sLbn0GJe+HBvVzAU3DK2ZGsrhczimt56za1Dqm41W/jnU8hA8QBf21zrCu2wElp7b8oJY8G7kFXaBSnQiyqTTQ9jnS+qhQSK5qCjbi0cChyQn6/f/NXM9+Xd6JDO/i5opF61cy3zGO3f304fDkv+/Cl51tuEaZliz/8qWDAFUgJ8PZ6c3iHhC8aK6rTtzlDjbKyU="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DoggyCraftDK_DramaCraft