name: DramaCraft
main: dogonfire.DramaCraft.DramaCraft
version: ${project.version}
api-version: 1.16
authors: [DogOnFire]
depend: 
  - WorldGuard
loadbefore:
  - GAListener 
commands:
    dramacraft:
        description: DramaCraft info
        usage: /DramaCraft [stuff]
        permissions: dramacraft.*
    dc:
        description: DramaCraft info
        usage: /dc
        permissions: dramacraft.*
    appoint:
        description: Appoint a rank
        usage: /appoint [stuff]
        permissions: dramacraft.*
    track:
        description: Track rebel transmitters or imperial statues
        usage: /track
        permissions: dramacraft.*
    guard:
        description: Checks bounties on rebels
        usage: /<command> [stuff]
        permissions: dramacraft.*
    bounty:
        description: Checks bounties on rebels
        usage: /bounty [stuff]
        permissions: dramacraft.*
    updateprefix:
        description: Update Empire prefix for a player
        usage: /<command> [stuff]
        permissions: dramacraft.*
    donate:
        description: Donate to your faction treasury
        usage: /donate <amount>
        permissions: dramacraft.*
    addbounty:
        description: Set a bounty on a player
        usage: /<command> [stuff]
        permissions: dramacraft.*
    imperials:
        description: vote for king & stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    rebels:
        description: vote for king & stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    vote:
        description: vote for king & stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
