name: DramaCraft
main: com.dogonfire.dramacraft.DramaCraft
version: ${project.version}
api-version: 1.14
authors: [DogOnFire]
depend: 
  - WorldGuard
loadbefore:
  - GAListener 
commands:
    dramacraft:
        description: DramaCraft info
        usage: /DramaCraft [stuff]
        permissions: dramacraft.*
    dc:
        description: DramaCraft info
        usage: /dc
        permissions: dramacraft.*
    appoint:
        description: Appoint a rank
        usage: /appoint [stuff]
        permissions: dramacraft.*
    track:
        description: Track rebel transmitters or imperial statues
        usage: /track
        permissions: dramacraft.*
    king:
        description: Do king stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    queen:
        description: Do queen stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    noble:
        description: Do imperial noble stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    innercircle:
        description: Do rebel innercircle stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    ringleader:
        description: Do Ringleader stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    imperial:
        description: vote for king & stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    rebel:
        description: vote for king & stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
    guard:
        description: Checks bounties on rebels
        usage: /<command> [stuff]
        permissions: dramacraft.*
    bounty:
        description: Checks bounties on rebels
        usage: /bounty [stuff]
        permissions: dramacraft.*
    updateprefix:
        description: Update Empire prefix for a player
        usage: /<command> [stuff]
        permissions: dramacraft.*
    donate:
        description: Donate to your faction treasury
        usage: /donate <amount>
        permissions: dramacraft.*
    law:
        description: View and propose laws for the Empire
        usage: /law
        permissions: dramacraft.*
    addbounty:
        description: Set a bounty on a player
        usage: /<command> [stuff]
        permissions: dramacraft.*
    vote:
        description: vote for king & stuff
        usage: /<command> [stuff]
        permissions: dramacraft.*
